name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '0.12.18'
      - run: npm install
      - run: node ./node_modules/vows/bin/vows test/tests.js -m "validate prototype pollution" --spec
